version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: symfony
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db